apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inventory-operator
  labels:
    akash.network: "true"
    app.kubernetes.io/name: akash
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/component: operator
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
      - nodes
      - pods
      - events
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ceph.rook.io
    resources:
      - cephclusters
      - cephblockpools
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - akash.network
    resources:
      - inventoryrequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - akash.network
    resources:
      - inventories
    verbs:
      - create
      - patch
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: feature-discovery-node
  labels:
    akash.network: "true"
    app.kubernetes.io/name: feature-discovery-node
    app.kubernetes.io/component: inventory
    app.kubernetes.io/part-of: operator
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
