---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-operator
  namespace: akash-services
  labels:
    akash.network: "true"
    app.kubernetes.io/name: akash
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/component: operator
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: feature-discovery-node
  namespace: akash-services
  labels:
    akash.network: "true"
    app.kubernetes.io/name: feature-discovery-node
    app.kubernetes.io/component: inventory
    app.kubernetes.io/part-of: operator
